### PR TITLE
Average air time, end on reset shot

### PR DESCRIPTION
**Pull request by nbgraham**
I haven't made an RL Plugin and wasn't able to run it

But just some ideas/fixes I had when using the plugin

- I wanted to know the average air time, so I tried to add that
- The timer doesn't stop on shot resets (in training) or scored goals (because the ball doesn't hit the ground), so tried to fix that
- Timer seems to keep going sometimes during pause so added another event I saw when I paused that made sense
- Often, when achieving a new best time, the last and best would be off by 0.01 even though it was the same run. Because they were calculated at different times (Reset vs Render). I moved it so all the calculation/setting happens in Reset

### CODE REVIEW

**Comment by BonesyWonesy** [comment]
Hey thanks for the PR and feedback! I was out of town so wasn't able to look into your PR. I'll try to look it over in the next week or so!

**Comment by BonesyWonesy** [comment]
Just wanted to give some feedback on the PR. I'm actually working on this now though and will hopefully try to have it wrapped up tonight. =)

**Comment by BonesyWonesy** [comment]
Hey @nbgraham, just wanted to let you know that I pushed a new version (v1.1) with this stuff in it, so I'm closing out your PR. Thanks for the contributions!

**Comment by nbgraham** [comment]
Awesome, thanks for responding and getting this idea in!

**Pull request closed without merging**
